### ISSUE TITLE
您好，utils文件里没有cam_calib_dict()这个函数，但您在DatasetLidarCamera.py中调用了这个函数，您能提供一下这个函数的定义吗？

### ISSUE THREAD

**Issue by 1187938150** [IIPCVLAB/LCCNet#1]

**Comment by LvXudong-HIT** [comment]
cam_calib_dict并不是utils.py中的函数，它只是一个字典变量，这个变量出现在KITTI360的dataloader里，我们在论文中并没有使用该数据集，因此我们删除了关于KITTI360数据的这部分代码。

**Comment by 1187938150** [comment]
谢谢您的回复，我跑通了evaluate_calib.py，但跑train_with_sacred.py时，提示没有losses这个模块

**Comment by LvXudong-HIT** [comment]
确实是忘记了上传losses这个模块，代码已更新

**Comment by 1187938150** [comment]
好的谢谢，可以跑通了
