### ISSUE TITLE
RuntimeError: cublas runtime error : the GPU program failed to execute at /pytorch/aten/src/THC/THCBlas.cu:258

### ISSUE THREAD

**Issue by Hliu0313** [IIPCVLAB/LCCNet#22]
解决方法：https://blog.csdn.net/weixin_41781121/article/details/109030372

**Comment by Hliu0313** [comment]
错误答案，不能解决问题！

**Comment by HXB-1997** [comment]
> 错误答案，不能解决问题！

请问您最后如何解决的？我是RTX4090+CUDA10.1+Ubuntu20.04+pytorch1.0.1 @Hliu0313
