### ISSUE TITLE
关于训练5个模型的问题

### ISSUE THREAD

**Issue by HXB-1997** [IIPCVLAB/LCCNet#23]
通过论文，我理解的是首先训练max_t=1.5，max_r=20的模型，之后用这个权值文件再训练max_t=1,max_r=10的模型，以此类推。可是我训练好max_t=1.5，max_r=20的模型后，将训练参数改为max_t=1,max_r=10后运行train_with_sacred.py，只显示full training time=0.00HR就结束了，请问可能是什么原因？

**Comment by HXB-1997** [comment]
我知道了，替换了weights路径后，还要把epoch改大，不能小于这个weights对用的epoch

**Comment by xuefeng1130** [comment]
> 我知道了，替换了weights路径后，还要把epoch改大，不能小于这个weights对用的epoch

您好，可以和您探讨一下训练的问题吗？我遇到了一些问题
