### ISSUE TITLE
How to train from zero?

### ISSUE THREAD

**Issue by libing64** [IIPCVLAB/LCCNet#6]
感谢分享，注意到LCCNet使用了预先训练好的kitti_iter12345.tar 并再次进行训练.
假如从零开始训练， 能分享下该怎么做吗？

**Comment by howtocodewang** [comment]
我并不太明白您说的使用了预训练好的模型进行再次训练。kitti_iter12345.tar本身就是在kitti上进行训练后的模型。

**Comment by libing64** [comment]
> 我并不太明白您说的使用了预训练好的模型进行再次训练。kitti_iter12345.tar本身就是在kitti上进行训练后的模型。

我现在看懂了，5组参数都可以从0开始训练 没问题了 
非常感谢 @howtocodewang

**Comment by qzsrh** [comment]
hello,麻烦问一下,数据的整体结构图是什么样.下载数据需要整理成什么样

**Comment by AbhiKhoyani** [comment]
> 

I just reevaluate it using KITTI. 
It should be :
`
base_folder > sequences > 00 > iamge_2 , velodyne, calib.txt

base_folder > poses > 00.txt
`
