### ISSUE TITLE
训练时使用测试数据挑选最优参数？

### ISSUE THREAD

**Issue by libing64** [IIPCVLAB/LCCNet#7]
代码虽然没有使用测试数据进行训练，但是使用了测试数据来挑选参数，感觉这样的结果不是很公正？

**Comment by howtocodewang** [comment]
我们并不理解“使用测试数据来挑选参数”具体指的是那一部分，麻烦明确一下，谢谢。

**Comment by libing64** [comment]
我的理解， 这一段是根据val loss的大小来挑选训练参数并保存，不知道我的理解是否有误？ @howtocodewang 


        # SAVE
        val_loss = total_val_loss / len(dataset_val)
        if val_loss < BEST_VAL_LOSS:
            BEST_VAL_LOSS = val_loss
            #_run.result = BEST_VAL_LOSS
            if _config['rescale_transl'] > 0:
                _run.result = total_val_t / len(dataset_val)
            else:
                _run.result = total_val_r / len(dataset_val)
            savefilename = f'{model_savepath}/checkpoint_r{_config["max_r"]:.2f}_t{_config["max_t"]:.2f}_e{epoch}_{val_loss:.3f}.tar'
            torch.save({
                'config': _config,
                'epoch': epoch,
                # 'state_dict': model.state_dict(), # single gpu
                'state_dict': model.module.state_dict(), # multi gpu
                'optimizer': optimizer.state_dict(),
                'train_loss': total_train_loss / len(dataset_train),
                'val_loss': total_val_loss / len(dataset_val),
            }, savefilename)
            print(f'Model saved as {savefilename}')
            if old_save_filename is not None:
                if os.path.exists(old_save_filename):
                    os.remove(old_save_filename)
            old_save_filename = savefilename

**Comment by howtocodewang** [comment]
是的，正如你所说，我们通过val_loss的大小判断存储的模型是否是最佳的。验证集不包含在训练集中，用验证集数据进行模型验证是可信且不会出现过拟合的问题。在训练过程中，模型的性能会随着优化过程而变化，每次训练集迭代完成后，都会使用验证集进行评估，以观测训练模型的泛化性从而调整参数，使得训练过程正常收敛。在每次训练集迭代完成后都会存储一个模型参数，为了节省存储开销，我们只保留在验证集上表现最好的模型，这个是极为公平的。而且在很多深度学习工作中都会使用这一方法来存储模型。

**Comment by libing64** [comment]
@howtocodewang 非常感谢您的耐心解答

**Comment by libing64** [comment]
https://www.bilibili.com/video/BV1Dh411x7hZ?spm_id_from=333.999.0.0
看了沐神的视频 确实是通用做法

**Comment by howtocodewang** [comment]
@libing64 是的，理想情况下，深度学习模型训练过程是一个逐渐下降并收敛的过程，但是实际上每个世代训练后的模型性能存在很强的波动，甚至在训练后期模型性能出现退化。最后阶段的模型性能未必就是最佳的，所以采用这种做法来保证存储的模型性能最佳。

**Comment by qzsrh** [comment]
hello,麻烦问一下,数据的整体结构图是什么样.数据文件夹需要整理成什么样

**Comment by StiphyJay** [comment]
> @libing64 是的，理想情况下，深度学习模型训练过程是一个逐渐下降并收敛的过程，但是实际上每个世代训练后的模型性能存在很强的波动，甚至在训练后期模型性能出现退化。最后阶段的模型性能未必就是最佳的，所以采用这种做法来保证存储的模型性能最佳。

你在使用00序列做验证集，同时又把00序列作为测试集，你相当于使用测试集上表现最好的参数来保存模型，然而测试集的gt应该在整个训练过程中保持为未知的，这明显就是非常不公平的设置，不是吗？

**Comment by Huleyun** [comment]
同时遇到两个奇怪问题：一是我使用提供的预训练权重测试00序列，每次的误差结果完全相同。二是我使用自己电脑训练出来权重，然后在00序列上进行检测，检测效果要远远好出预期，几乎100%，这应该在代码上存在一些问题。

这是我自己训练120epochs，角度误差20度，距离误差1.5m，事先踢掉00序列，用01序列作验证集的效果
![120epochs-20度1 5m训练-20度1 5m测试](https://github.com/IIPCVLAB/LCCNet/assets/30621422/814e2266-b1d0-447e-a187-a344894ab143)

下面这两个分别是使用代码提供的预训练权重iter_1在角度误差20度，距离误差1.5m和角度误差1度，距离误差0.1度下作的测试，两者的输出结果一模一样，这很奇怪。

![Kitti_iter1-120epochs-20度1 5m训练-20度1 5m测试](https://github.com/IIPCVLAB/LCCNet/assets/30621422/919846ec-0ded-45f9-bd06-ba863775ddcb)


![Kitti_iter1-120epochs-20度1 5m训练-1度0 1m测试](https://github.com/IIPCVLAB/LCCNet/assets/30621422/732913e5-9fad-4f6b-a2b1-5bd2dc6ca14f)
